name: parallel jobs
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World from GitHub Actions ðŸš€"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World from GitHub Actions ðŸš€"

  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World from GitHub Actions ðŸš€"

  job-4:
    needs: job-3
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World from GitHub Actions ðŸš€"  